# Generated by Django 4.1.7 on 2023-03-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('producto', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=12)),
                ('marca', models.CharField(max_length=30)),
            ],
        ),
    ]
