# Generated by Django 4.1.7 on 2023-03-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Producto2',
        ),
    ]
